version: "3.9"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: pk/billing-context
    ports:
      - "9000:9000"
    restart: always
    environment:
      - "SPRING_PROFILES_ACTIVE=hml"
    depends_on:
      - postgres
    networks:
      - backend
  postgres:
    image: postgres:9.6
    restart: always
    ports:
    - "5432:5432"
    environment:
      - POSTGRES_DB=billing-db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - backend

volumes:
  postgres-data:

networks:
  backend:
