kind: Deployment
apiVersion: apps/v1
metadata:
  namespace: billing-develop
  name: whoami
  labels:
    app: whoami
spec:
  replicas: 2
  selector:
    matchLabels:
      app: whoami
  template:
    metadata:
      labels:
        app: whoami
    spec:
      containers:
        - name: whoami
          image: 133876145150.dkr.ecr.us-east-1.amazonaws.com/gitworkflow-ci-cd-poc
          ports:
            - name: web
              containerPort: 80