kind: Deployment
apiVersion: apps/v1
metadata:
  namespace: billing-develop
  name: billing-service
  labels:
    app: billing-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: billing-service
  template:
    metadata:
      labels:
        app: billing-service
    spec:
      containers:
        - name: billing-service
          image: 133876145150.dkr.ecr.us-east-1.amazonaws.com/gitworkflow-ci-cd-poc
          ports:
            - name: web
              containerPort: 80