name: Backport
on:
  pull_request:
    types:
      - closed

env:
  GIT_RELEASE_BOT_NAME: pk-boot
  GIT_RELEASE_BOT_EMAIL: pk-boot@playkids.com
  REVIEWERS_TEAMS: pkapp-platforms

jobs:
  backport:
    runs-on: ubuntu-latest
    name: Backport
    steps:
      - name: Backport commit
        uses: qcastel/github-actions-backport@v0.7.0
        with:
          backport-branches-regex: "releases*"

          reviewers-teams: "['pkapp-platforms']"
          
          git-release-bot-name: "Git-action-boot"
          git-release-bot-email: "git-action-boot@playkids.com"
          
          access-token: ${{ secrets.GITHUB_ACCESS_TOKEN }}

# https://github.com/qcastel/github-actions-backport