name: Container
on: push

jobs:
  build-container:
    runs-on: ubuntu-latest
    container:
      image: adoptopenjdk/openjdk11-openj9:jdk-11.0.10_9_openj9-0.24.0-alpine
    steps:
      - name: Docker log
        run: |
          java -version