name: Docker CI on ECR

on:
  push:
    branches: [ main ]
  pull_request: #TEMPORARIO APENAS PRA TEST
    branches: [ main ]

env:
  BRANCH_NAME: ${{GITHUB_REF##*/}}
  NAMESPACE: 'billing-develop'
  PROJECT_NAME: ${{GITHUB_REPOSITORY##*/}}
  ECR: 133876145150.dkr.ecr.us-east-1.amazonaws.com
  REPO_NAME: ${{ github.event.repository.name }}

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build, tag, and push image to Amazon ECR
        id: build-image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: ${{ github.event.repository.name }}
          # IMAGE_TAG: ${{ github.sha }}
        run: |
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:${GITHUB_SHA::7} --file Dockerfile .
          echo "Pushing image to ECR..."
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:${GITHUB_SHA::7}
          echo "::set-output name=image::$ECR_REGISTRY/$ECR_REPOSITORY:${GITHUB_SHA::7}"

      - name: xx
        run: envsubst <./cicd/deployment.yaml.tmpl >./cicd/deployment.yaml

      - name: Push manifests to Flux repo
        uses: dmnemec/copy_file_to_another_repo_action@v1.1.1 
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
        with:
          source_file: 'cicd/deployment.yaml'
          destination_repo: 'Playkids/flux-repo'
          destination_branch: 'develop'
          destination_folder: 'deployments/gitworkflow-ci-cd-poc'
          user_email: 'cicd@playkids.com'
          user_name: 'CI CD Worker'
          commit_message: 'Updating application on cluster.'

      # - name: DEBUG
      #   run: |
      #     echo "GITHUB_SHA: ${GITHUB_SHA::7}"
      #     echo "github.ref: ${{ github.ref }}"
      #     echo "GITHUB_REF: ${GITHUB_REF}"
      #     echo "GITHUB_REPOSITORY: ${GITHUB_REPOSITORY}"
      #     echo "GITHUB_ACTOR: ${GITHUB_ACTOR}"
      #     echo "Repo name: ${{ github.event.repository.name }}"
      #     echo "docker build name: ${GITHUB_REPOSITORY}-${GITHUB_REF}/${{ github.event.repository.name }}"
      # - name: Build image
      #   run: docker build . --file Dockerfile -t ${GITHUB_REPOSITORY}-${GITHUB_REF}/${{ github.event.repository.name }}

      # - name: Tag image
      #   run: docker tag ${GITHUB_REPOSITORY}-${GITHUB_REF}/${{ github.event.repository.name }}:latest ${GITHUB_REPOSITORY}-${GITHUB_REF}/${{ github.event.repository.name }}:${GITHUB_REF}-${GITHUB_SHA::7}

