name: Container
on: push

jobs:
  build-container:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Git Properties
        run: |
          echo "SHORT SHA: ${GITHUB_SHA::7}"
          echo "SHORT REF: ${GITHUB_REF}"


    # container:
    #   image: adoptopenjdk/openjdk11-openj9:jdk-11.0.10_9_openj9-0.24.0-alpine
    # steps:
    #   - name: Docker log
    #     run: |
    #       java -version