name: Container
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]    

env:
  IMAGE_NAME: ${GITHUB_REPOSITORY}-${GITHUB_REF}/${{ github.event.repository.name }}

jobs:
  build-container:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Build image
        run: docker build . --file Dockerfile --tag $IMAGE_NAME
      # --build-arg PROFILE=${PROFILE} --tag my-image-name:$(date +%s)

      # - name: Build and push
      #   id: docker_build
      #   uses: docker/build-push-action@v2
      #   with:
      #     context: ./
      #     file: ./Dockerfile
      #     push: true
      #     tags: pk/billing-context:latest
          
      - name: Git Properties
        run: |
          echo "GITHUB_SHA: ${GITHUB_SHA::7}"
          echo "GITHUB_REF: ${GITHUB_REF}"
          echo "GITHUB_REPOSITORY: ${GITHUB_REPOSITORY}"
          echo "GITHUB_ACTOR: ${GITHUB_ACTOR}"
          echo "Repo name: ${{ github.event.repository.name }}"
          echo "docker build name: ${GITHUB_REPOSITORY}-${GITHUB_REF}/${{ github.event.repository.name }}"

