name: Docker CI on ECR

on:
  push:
    branches: [ main ]
  pull_request: #TEMPORARIO APENAS PRA TEST
    branches: [ main ]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build, tag, and push image to Amazon ECR
        id: build-image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: ${GITHUB_REPOSITORY}
          IMAGE_TAG: ${GITHUB_REF}-${GITHUB_SHA::7}
        run: |
          echo "GITHUB_SHA: ${GITHUB_SHA::7}"
          echo "AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}"
          echo "AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}"
          echo "GITHUB_REF: ${GITHUB_REF}"
          echo "GITHUB_REPOSITORY: ${GITHUB_REPOSITORY}"
          echo "GITHUB_ACTOR: ${GITHUB_ACTOR}"
          echo "Repo name: ${{ github.event.repository.name }}"
          echo "docker build name: ${GITHUB_REPOSITORY}-${GITHUB_REF}/${{ github.event.repository.name }}"
        # run: |
        #   docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG --file Dockerfile .
        #   echo "Pushing image to ECR..."
        #   docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
        #   echo "::set-output name=image::$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG"


      - name: DEBUG
        run: |
          echo "GITHUB_SHA: ${GITHUB_SHA::7}"
          echo "AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}"
          echo "AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}"
          echo "GITHUB_REF: ${GITHUB_REF}"
          echo "GITHUB_REPOSITORY: ${GITHUB_REPOSITORY}"
          echo "GITHUB_ACTOR: ${GITHUB_ACTOR}"
          echo "Repo name: ${{ github.event.repository.name }}"
          echo "docker build name: ${GITHUB_REPOSITORY}-${GITHUB_REF}/${{ github.event.repository.name }}"
      # - name: Build image
      #   run: docker build . --file Dockerfile -t ${GITHUB_REPOSITORY}-${GITHUB_REF}/${{ github.event.repository.name }}

      # - name: Tag image
      #   run: docker tag ${GITHUB_REPOSITORY}-${GITHUB_REF}/${{ github.event.repository.name }}:latest ${GITHUB_REPOSITORY}-${GITHUB_REF}/${{ github.event.repository.name }}:${GITHUB_REF}-${GITHUB_SHA::7}

