name: Container
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]    

jobs:
  build-container:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      # - name: Build the Docker image
      # - run: docker build -t ${GITHUB_REPOSITORY}- . --file Dockerfile --tag my-image-name:$(date +%s)
      # --build-arg PROFILE=${PROFILE}

      # - name: Build and push
      #   id: docker_build
      #   uses: docker/build-push-action@v2
      #   with:
      #     context: ./
      #     file: ./Dockerfile
      #     push: true
      #     tags: pk/billing-context:latest
          
      - name: Git Properties
        run: |
          echo "GITHUB_SHA: ${GITHUB_SHA::7}"
          echo "GITHUB_REF: ${GITHUB_REF}"
          echo "GITHUB_REPOSITORY: ${GITHUB_REPOSITORY}"
          echo "GITHUB_ACTOR: ${GITHUB_ACTOR}"
          echo "GITHUB_ACTOR: ${{ github.event.repository.name }}"

