name: Docker CI

on:
  push:
    branches: [ main ]
  # pull_request: TEMPORARIO APENAS PRA TEST
  #   branches: [ main ]

jobs:
  build-container:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Build image
        run: docker build . --file Dockerfile -t ${GITHUB_REPOSITORY}-${GITHUB_REF}/${{ github.event.repository.name }}

      - name: Tag image
        run: docker tag ${GITHUB_REPOSITORY}-${GITHUB_REF}/${{ github.event.repository.name }}:latest ${GITHUB_REPOSITORY}-${GITHUB_REF}/${{ github.event.repository.name }}:${GITHUB_REF}-${GITHUB_SHA::7}

      # - name: Push to ECR
      #   id: ecr
      #   uses: jwalton/gh-ecr-login@v1
      #   with:
      #     access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
      #     secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      #     region: us-east-1
      # - name: Push to ECR
      #   run: |
      #     docker tag my-image ${{ steps.ecr.outputs.account }}.dkr.ecr.us-east-1.amazonaws.com/my-image:v1
      #     docker push ${{ steps.ecr.outputs.account }}.dkr.ecr.us-east-1.amazonaws.com/my-image:v1

      # - name: Push to ECR
      #   run: docker build . --file Dockerfile --tag ${GITHUB_REPOSITORY}-${GITHUB_REF}/${{ github.event.repository.name }}

      - name: TEST - Git Properties
        run: |
          echo "GITHUB_SHA: ${GITHUB_SHA::7}"
          echo "GITHUB_REF: ${GITHUB_REF}"
          echo "GITHUB_REPOSITORY: ${GITHUB_REPOSITORY}"
          echo "GITHUB_ACTOR: ${GITHUB_ACTOR}"
          echo "Repo name: ${{ github.event.repository.name }}"
          echo "docker build name: ${GITHUB_REPOSITORY}-${GITHUB_REF}/${{ github.event.repository.name }}"


