name: Test pipeline

on: [push]

jobs:
  run-shell-command:
    runs-on: ubuntu-latest
    steps: 
      - name: multiline script 
        run: |
           gradle clean
           gradle build
           gradle test
