name: Run Gradle Build on push event

on:
  push:
  pull_request: 
    types:
      - opened
      - reopened

jobs:
  gradle-project:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        jdk: [11]
    runs-on: ${{ matrix.os }}
    env:
      JDK_VERSION: ${{ matrix.jdk }}    
    # environment:
      # name: hml
      # url: 'http://app-hml.com.br'
    steps: 
      - name: Checkout repository
        uses: actions/checkout@v2
