name: Run Gradle Build on push event

on:
  pull_request: 
    types:
      - opened
      - reopened
      - synchronize

jobs:
  gradle-project:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        jdk: [11]
    runs-on: ${{ matrix.os }}
    steps: 
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: ${{ matrix.jdk }}
          distribution: 'adopt'        
