name: Run Gradle Build on push event

on: push

# on:
#   push:
#     branches:
#       - develop

jobs:
  gradle-project:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        jdk: [11]
    runs-on: ${{ matrix.os }}
    env:
      JDK_VERSION: ${{ matrix.jdk }}    
    # environment:
      # name: hml
      # url: 'http://app-hml.com.br'
    steps: 
      - name: gradle version show
        run: gradle -v


  # steps:
  #   - name: Checkout Repo
  #     uses: actions/checkout@v2
  #   ...
  #   - name: Setup Java
  #     uses: actions/setup-java@v1
  #     with:
  #       java-version: ${{ matrix.jdk }}